CREATE DATABASE IF NOT EXISTS cartilla;
USE cartilla;

CREATE TABLE IF NOT EXISTS raza(
	RAZ_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    RAZ_NOMBRE VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS tipousu(
    TIU_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    TIU_NOMBRE VARCHAR(50) NOT NULL unique
);
CREATE TABLE IF NOT EXISTS programa(
    PRG_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRG_CLAVE VARCHAR(12) NOT NULL unique,
    PRG_NOMBRE VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS menu(
    MEN_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    MEN_CLAVE VARCHAR(10) NOT NULL unique,
    MEN_NOMBRE VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS especialidad(
	ESP_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    ESP_NOMBRE VARCHAR(50) NOT NULL,
    ESP_DESC TEXT
);
CREATE TABLE IF NOT EXISTS vacuna(
    VAC_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    RAZ_NUMCTRL INTEGER(9),
    VAC_NOMBRE VARCHAR(60) NOT NULL,
    VAC_DESC TEXT,
	CONSTRAINT vacuna1 FOREIGN KEY (RAZ_NUMCTRL) REFERENCES raza(RAZ_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS proveedor(
    PRV_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRV_NOMBRE VARCHAR(70) NOT NULL,
    PRV_PROPIETARIO VARCHAR(70) NOT NULL,
    PRV_CELULAR BIGINT(10) NOT NULL unique,
    PRV_TELOFICINA BIGINT(10) NOT NULL unique,
    PRV_CORREO VARCHAR(60) NOT NULL,
    PRV_CONTRA VARCHAR(100) NOT NULL,
    TIU_NUMCTRL INTEGER(9),
	CONSTRAINT proveedor1 FOREIGN KEY (TIU_NUMCTRL) REFERENCES tipousu(TIU_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS propietario(
    PRO_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRO_NOMBRE VARCHAR(50) NOT NULL unique,
    PRO_CELULAR BIGINT(10) NOT NULL,
    PRO_CORREO VARCHAR(60) NOT NULL,
    PRO_CONTRA VARCHAR(100) NOT NULL,
	TIU_NUMCTRL INTEGER(9),
	CONSTRAINT propietario1 FOREIGN KEY (TIU_NUMCTRL) REFERENCES tipousu(TIU_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS mascota(
    MAS_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRO_NUMCTRL INTEGER(9),
    MAS_NOMBRE VARCHAR(40) NOT NULL,
    MAS_FECHANAC date,
    MAS_RAZA VARCHAR(50) NOT NULL,
    RAZ_NUMCTRL INTEGER(9),
    CONSTRAINT mascota1 FOREIGN KEY (PRO_NUMCTRL) REFERENCES propietario(PRO_NUMCTRL),
    CONSTRAINT mascota2 FOREIGN KEY (RAZ_NUMCTRL) REFERENCES raza(RAZ_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS sucxprv(
    SXP_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRV_NUMCTRL INTEGER(9),
    SXP_NOMBRE VARCHAR(50) NOT NULL,
    SXP_DIRECCION VARCHAR(70) NOT NULL,
    SXP_COLONIA VARCHAR(40)  NOT NULL,
    SXP_CP VARCHAR(5)NOT NULL,
    SXP_ENCARGADO VARCHAR(50),
    SXP_TELEFONO BIGINT(10)NOT NULL,
    SXP_LAT VARCHAR(10),
    SXP_LON VARCHAR(10),
	CONSTRAINT sucxprv1 FOREIGN KEY (PRV_NUMCTRL) REFERENCES proveedor(PRV_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS serxmas(
    SXM_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    MAS_NUMCTRL INTEGER(9),
    SXM_FECHA date,
    SXM_PRECIO float(10,2)  NOT NULL,
	CONSTRAINT serxmas1 FOREIGN KEY (MAS_NUMCTRL) REFERENCES mascota(MAS_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS caldia(
    SXP_NUMCTRL INTEGER(9),
    CAD_DIA SET('1','2','3','4','5','6','7'),
	CONSTRAINT caldia1 FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS calfecha(
    SXP_NUMCTRL INTEGER(9),
    CAF_FECHA date,
	CONSTRAINT calfecha1 FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS horario(
    HOR_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    SXP_NUMCTRL INTEGER(9) ,
    HOR_TURNO SET('M','V','C'),
    HOR_HORAINI time NOT NULL,
    HOR_HORAFIN time NOT NULL,
    HOR_TIPO time NOT NULL,
    HOR_DIA SET('1','2','3','4','5','6','7'),
	CONSTRAINT horario1 FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS masfoto(
    MAF_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    MAS_NUMCTRL INTEGER(9),
    MAF_FOTO VARCHAR(50),
	CONSTRAINT masfoto1 FOREIGN KEY (MAS_NUMCTRL) REFERENCES mascota(MAS_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS proxmen(
    PXM_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    PRG_NUMCTRL INTEGER(9),
    MEN_NUMCTRL INTEGER(9),
	CONSTRAINT proxmen1 FOREIGN KEY (PRG_NUMCTRL) REFERENCES programa(PRG_NUMCTRL),
	CONSTRAINT proxmen2 FOREIGN KEY (MEN_NUMCTRL) REFERENCES menu(MEN_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS proxusu(
    TIU_NUMCTRL INTEGER(9),
    PRG_NUMCTRL INTEGER(9),
	CONSTRAINT proxusu1 FOREIGN KEY (TIU_NUMCTRL) REFERENCES tipousu(TIU_NUMCTRL),
	CONSTRAINT proxusu2 FOREIGN KEY (PRG_NUMCTRL) REFERENCES programa(PRG_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS vacxmas(
    VXM_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
	MAS_NUMCTRL INTEGER(9),
    PRV_NUMCTRL INTEGER(9) default null,
    VAC_NUMCTRL INTEGER(9),
    VXM_FECHA date,
	VXM_FECHAAPLICA date,
    CONSTRAINT vacxmas1 FOREIGN KEY (MAS_NUMCTRL) REFERENCES mascota(MAS_NUMCTRL),
	CONSTRAINT vacxmas2 FOREIGN KEY (VAC_NUMCTRL) REFERENCES vacuna(VAC_NUMCTRL),
	CONSTRAINT vacxmas3 FOREIGN KEY (PRV_NUMCTRL) REFERENCES proveedor(PRV_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS agenda(
    AGE_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    SXP_NUMCTRL INTEGER(9),
    HOR_NUMCTRL INTEGER(9),
    MAS_NUMCTRL INTEGER(9),
    AGE_FECHA date,
    AGE_ESTATUS SET('1','2'),
	CONSTRAINT agenda1 FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL),
	CONSTRAINT agenda2 FOREIGN KEY (HOR_NUMCTRL) REFERENCES horario(HOR_NUMCTRL),
	CONSTRAINT agenda3 FOREIGN KEY (MAS_NUMCTRL) REFERENCES mascota(MAS_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS serxsuc(
	SXS_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    SXP_NUMCTRL INTEGER(9),
    SXS_NOMBRE VARCHAR(70) NOT NULL,
    SXS_DESCRIPTION TEXT,
    SXS_PRECIO FLOAT(11,2),
	CONSTRAINT serxsuc FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL)
);
CREATE TABLE IF NOT EXISTS espxsuc(
	ESP_NUMCTRL INTEGER(9) PRIMARY KEY AUTO_INCREMENT,
    SXP_NUMCTRL INTEGER(9),
    CONSTRAINT espxsuc FOREIGN KEY (SXP_NUMCTRL) REFERENCES sucxprv(SXP_NUMCTRL)
);
INSERT INTO tipousu (TIU_NOMBRE) VALUES ("Proveedor"),("Propietario");